apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bz27d8yg1-go
  janus-idp.io/tekton: bz27d8yg1-go
  backstage.io/kubernetes-id: bz27d8yg1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bz27d8yg1-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
